DROP DATABASE IF EXISTS burgers_db2;
CREATE DATABASE burgers_db2;
-- USE burgers_db2;

-- CREATE TABLE burgers(
-- 	id INT AUTO_INCREMENT NOT NULL,
-- 	burger_name VARCHAR(100) NOT NULL,
-- 	devoured BOOLEAN NOT NULL,
-- 	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- 	PRIMARY KEY(id)
-- );